version: '3'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
  postgres:
      image: postgres:14.3
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'
      volumes: 
        - ./.sql:/docker-entrypoint-initdb.d
        - ./.postgres-data:/var/lib/postgresql/data